"""Created DateTime fields on baseModel

Revision ID: 93c19b54d8b3
Revises: 4146abfa684f
Create Date: 2023-07-09 17:30:27.742313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c19b54d8b3'
down_revision = '4146abfa684f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_category', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('product_category', 'updated_at')
    op.drop_column('product_category', 'created_at')
    # ### end Alembic commands ###
