"""Update models

Revision ID: abbdadc32ba7
Revises: 48065be3241d
Create Date: 2023-07-08 13:15:29.337051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbdadc32ba7'
down_revision = '48065be3241d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
