"""Fixing last Migration

Revision ID: c2da72df36e0
Revises: 93c19b54d8b3
Create Date: 2023-07-09 17:44:44.100854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2da72df36e0'
down_revision = '93c19b54d8b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
